[package]
name = "docs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
# fancy error messages
miette = { workspace = true, features = ["fancy"] }
opener = "0.5"

